{{ $components := list "frontend" "backend" "ytproxy" "varnish" }}
{{- range $components -}}
  {{- include "common.values.setup" (index $.Subcharts .) }}
  {{- with (index $.Values .) }}
    {{- with .image }}
           {{- $_ := set . "tag" (default $.Chart.AppVersion .tag) -}}
    {{- end -}}
    {{- include "common.all" (index $.Subcharts .) }}
  {{- end -}}
{{- end -}}

