---
apiVersion: v2
description: Piped is an alternative privacy-friendly YouTube frontend which is efficient by design.
name: piped
home: https://github.com/TeamPiped/Piped-Kubernetes
sources:
  - https://github.com/TeamPiped/Piped
  - https://github.com/TeamPiped/Piped-Backend
  - https://github.com/TeamPiped/piped-proxy
keywords:
  - streaming
version: 2.0.1
appVersion: latest
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: Skyler Mäntysaari
    email: samip5@users.noreply.github.com
    url: https://github.com/samip5
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.2.0
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: The backend configmap generation (GH issue: https://github.com/TeamPiped/Piped-Kubernetes/issues/2)
